// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/inference/v1/inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Precision identifies the numeric precision a model worker should run inference at.
type Precision int32

const (
	Precision_PRECISION_UNSPECIFIED Precision = 0
	Precision_PRECISION_FP32        Precision = 1
	Precision_PRECISION_FP16        Precision = 2
	Precision_PRECISION_INT8        Precision = 3
	Precision_PRECISION_INT4        Precision = 4
)

// Enum value maps for Precision.
var (
	Precision_name = map[int32]string{
		0: "PRECISION_UNSPECIFIED",
		1: "PRECISION_FP32",
		2: "PRECISION_FP16",
		3: "PRECISION_INT8",
		4: "PRECISION_INT4",
	}
	Precision_value = map[string]int32{
		"PRECISION_UNSPECIFIED": 0,
		"PRECISION_FP32":        1,
		"PRECISION_FP16":        2,
		"PRECISION_INT8":        3,
		"PRECISION_INT4":        4,
	}
)

func (x Precision) Enum() *Precision {
	p := new(Precision)
	*p = x
	return p
}

func (x Precision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Precision) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inference_v1_inference_proto_enumTypes[0].Descriptor()
}

func (Precision) Type() protoreflect.EnumType {
	return &file_proto_inference_v1_inference_proto_enumTypes[0]
}

func (x Precision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Precision.Descriptor instead.
func (Precision) EnumDescriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

// Priority controls scheduling order in the job queue.
type Priority int32

const (
	Priority_PRIORITY_NORMAL   Priority = 0
	Priority_PRIORITY_HIGH     Priority = 1
	Priority_PRIORITY_CRITICAL Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_NORMAL",
		1: "PRIORITY_HIGH",
		2: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_NORMAL":   0,
		"PRIORITY_HIGH":     1,
		"PRIORITY_CRITICAL": 2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inference_v1_inference_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_inference_v1_inference_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

type InferenceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	VehicleId          string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	ModelName          string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion       string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // empty means "latest deployed version"
	PreferredPrecision Precision              `protobuf:"varint,5,opt,name=preferred_precision,json=preferredPrecision,proto3,enum=inference.v1.Precision" json:"preferred_precision,omitempty"`
	Features           []float32              `protobuf:"fixed32,6,rep,packed,name=features,proto3" json:"features,omitempty"`
	Priority           Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=inference.v1.Priority" json:"priority,omitempty"`
	SubmittedAtUnixMs  int64                  `protobuf:"varint,8,opt,name=submitted_at_unix_ms,json=submittedAtUnixMs,proto3" json:"submitted_at_unix_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *InferenceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InferenceRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *InferenceRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *InferenceRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *InferenceRequest) GetPreferredPrecision() Precision {
	if x != nil {
		return x.PreferredPrecision
	}
	return Precision_PRECISION_UNSPECIFIED
}

func (x *InferenceRequest) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *InferenceRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_NORMAL
}

func (x *InferenceRequest) GetSubmittedAtUnixMs() int64 {
	if x != nil {
		return x.SubmittedAtUnixMs
	}
	return 0
}

type InferenceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ModelName      string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion   string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	PrecisionUsed  Precision              `protobuf:"varint,5,opt,name=precision_used,json=precisionUsed,proto3,enum=inference.v1.Precision" json:"precision_used,omitempty"`
	Output         []float32              `protobuf:"fixed32,6,rep,packed,name=output,proto3" json:"output,omitempty"`
	PredictedLabel string                 `protobuf:"bytes,7,opt,name=predicted_label,json=predictedLabel,proto3" json:"predicted_label,omitempty"`
	Confidence     float32                `protobuf:"fixed32,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	LatencyMs      int64                  `protobuf:"varint,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	QueueTimeMs    int64                  `protobuf:"varint,10,opt,name=queue_time_ms,json=queueTimeMs,proto3" json:"queue_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InferenceResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *InferenceResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *InferenceResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *InferenceResponse) GetPrecisionUsed() Precision {
	if x != nil {
		return x.PrecisionUsed
	}
	return Precision_PRECISION_UNSPECIFIED
}

func (x *InferenceResponse) GetOutput() []float32 {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *InferenceResponse) GetPredictedLabel() string {
	if x != nil {
		return x.PredictedLabel
	}
	return ""
}

func (x *InferenceResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InferenceResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *InferenceResponse) GetQueueTimeMs() int64 {
	if x != nil {
		return x.QueueTimeMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActiveWorkers int32                  `protobuf:"varint,2,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	QueueDepth    int32                  `protobuf:"varint,3,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	RouterVersion string                 `protobuf:"bytes,4,opt,name=router_version,json=routerVersion,proto3" json:"router_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *HealthResponse) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *HealthResponse) GetRouterVersion() string {
	if x != nil {
		return x.RouterVersion
	}
	return ""
}

type RegisterWorkerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SupportedModels []string               `protobuf:"bytes,2,rep,name=supported_models,json=supportedModels,proto3" json:"supported_models,omitempty"`
	GpuAvailable    bool                   `protobuf:"varint,3,opt,name=gpu_available,json=gpuAvailable,proto3" json:"gpu_available,omitempty"`
	MaxPrecision    Precision              `protobuf:"varint,4,opt,name=max_precision,json=maxPrecision,proto3,enum=inference.v1.Precision" json:"max_precision,omitempty"`
	Endpoint        string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // base URL the router forwards inference HTTP calls to
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetSupportedModels() []string {
	if x != nil {
		return x.SupportedModels
	}
	return nil
}

func (x *RegisterWorkerRequest) GetGpuAvailable() bool {
	if x != nil {
		return x.GpuAvailable
	}
	return false
}

func (x *RegisterWorkerRequest) GetMaxPrecision() Precision {
	if x != nil {
		return x.MaxPrecision
	}
	return Precision_PRECISION_UNSPECIFIED
}

func (x *RegisterWorkerRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterWorkerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_inference_v1_inference_proto protoreflect.FileDescriptor

const file_proto_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\"proto/inference/v1/inference.proto\x12\finference.v1\"\xdf\x02\n" +
	"\x10InferenceRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12H\n" +
	"\x13preferred_precision\x18\x05 \x01(\x0e2\x17.inference.v1.PrecisionR\x12preferredPrecision\x12\x1a\n" +
	"\bfeatures\x18\x06 \x03(\x02R\bfeatures\x122\n" +
	"\bpriority\x18\a \x01(\x0e2\x16.inference.v1.PriorityR\bpriority\x12/\n" +
	"\x14submitted_at_unix_ms\x18\b \x01(\x03R\x11submittedAtUnixMs\"\xf7\x02\n" +
	"\x11InferenceResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12>\n" +
	"\x0eprecision_used\x18\x05 \x01(\x0e2\x17.inference.v1.PrecisionR\rprecisionUsed\x12\x16\n" +
	"\x06output\x18\x06 \x03(\x02R\x06output\x12'\n" +
	"\x0fpredicted_label\x18\a \x01(\tR\x0epredictedLabel\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x03R\tlatencyMs\x12\"\n" +
	"\rqueue_time_ms\x18\n" +
	" \x01(\x03R\vqueueTimeMs\"\x0f\n" +
	"\rHealthRequest\"\x97\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0eactive_workers\x18\x02 \x01(\x05R\ractiveWorkers\x12\x1f\n" +
	"\vqueue_depth\x18\x03 \x01(\x05R\n" +
	"queueDepth\x12%\n" +
	"\x0erouter_version\x18\x04 \x01(\tR\rrouterVersion\"\xde\x01\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12)\n" +
	"\x10supported_models\x18\x02 \x03(\tR\x0fsupportedModels\x12#\n" +
	"\rgpu_available\x18\x03 \x01(\bR\fgpuAvailable\x12<\n" +
	"\rmax_precision\x18\x04 \x01(\x0e2\x17.inference.v1.PrecisionR\fmaxPrecision\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"4\n" +
	"\x16RegisterWorkerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*v\n" +
	"\tPrecision\x12\x19\n" +
	"\x15PRECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePRECISION_FP32\x10\x01\x12\x12\n" +
	"\x0ePRECISION_FP16\x10\x02\x12\x12\n" +
	"\x0ePRECISION_INT8\x10\x03\x12\x12\n" +
	"\x0ePRECISION_INT4\x10\x04*I\n" +
	"\bPriority\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x00\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x01\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x022\xd6\x02\n" +
	"\x10InferenceService\x12J\n" +
	"\aPredict\x12\x1e.inference.v1.InferenceRequest\x1a\x1f.inference.v1.InferenceResponse\x12T\n" +
	"\rStreamPredict\x12\x1e.inference.v1.InferenceRequest\x1a\x1f.inference.v1.InferenceResponse(\x010\x01\x12C\n" +
	"\x06Health\x12\x1b.inference.v1.HealthRequest\x1a\x1c.inference.v1.HealthResponse\x12[\n" +
	"\x0eRegisterWorker\x12#.inference.v1.RegisterWorkerRequest\x1a$.inference.v1.RegisterWorkerResponseBfZdgithub.com/rashmioffcialpage/distributed-ml-inference-platform/shared/proto/inference/v1;inferencev1b\x06proto3"

var (
	file_proto_inference_v1_inference_proto_rawDescOnce sync.Once
	file_proto_inference_v1_inference_proto_rawDescData []byte
)

func file_proto_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_v1_inference_proto_rawDesc), len(file_proto_inference_v1_inference_proto_rawDesc)))
	})
	return file_proto_inference_v1_inference_proto_rawDescData
}

var file_proto_inference_v1_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_inference_v1_inference_proto_goTypes = []any{
	(Precision)(0),                 // 0: inference.v1.Precision
	(Priority)(0),                  // 1: inference.v1.Priority
	(*InferenceRequest)(nil),       // 2: inference.v1.InferenceRequest
	(*InferenceResponse)(nil),      // 3: inference.v1.InferenceResponse
	(*HealthRequest)(nil),          // 4: inference.v1.HealthRequest
	(*HealthResponse)(nil),         // 5: inference.v1.HealthResponse
	(*RegisterWorkerRequest)(nil),  // 6: inference.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 7: inference.v1.RegisterWorkerResponse
}
var file_proto_inference_v1_inference_proto_depIdxs = []int32{
	0, // 0: inference.v1.InferenceRequest.preferred_precision:type_name -> inference.v1.Precision
	1, // 1: inference.v1.InferenceRequest.priority:type_name -> inference.v1.Priority
	0, // 2: inference.v1.InferenceResponse.precision_used:type_name -> inference.v1.Precision
	0, // 3: inference.v1.RegisterWorkerRequest.max_precision:type_name -> inference.v1.Precision
	2, // 4: inference.v1.InferenceService.Predict:input_type -> inference.v1.InferenceRequest
	2, // 5: inference.v1.InferenceService.StreamPredict:input_type -> inference.v1.InferenceRequest
	4, // 6: inference.v1.InferenceService.Health:input_type -> inference.v1.HealthRequest
	6, // 7: inference.v1.InferenceService.RegisterWorker:input_type -> inference.v1.RegisterWorkerRequest
	3, // 8: inference.v1.InferenceService.Predict:output_type -> inference.v1.InferenceResponse
	3, // 9: inference.v1.InferenceService.StreamPredict:output_type -> inference.v1.InferenceResponse
	5, // 10: inference.v1.InferenceService.Health:output_type -> inference.v1.HealthResponse
	7, // 11: inference.v1.InferenceService.RegisterWorker:output_type -> inference.v1.RegisterWorkerResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_inference_v1_inference_proto_init() }
func file_proto_inference_v1_inference_proto_init() {
	if File_proto_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_v1_inference_proto_rawDesc), len(file_proto_inference_v1_inference_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_v1_inference_proto_depIdxs,
		EnumInfos:         file_proto_inference_v1_inference_proto_enumTypes,
		MessageInfos:      file_proto_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_v1_inference_proto = out.File
	file_proto_inference_v1_inference_proto_goTypes = nil
	file_proto_inference_v1_inference_proto_depIdxs = nil
}
