# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from inference.v1 import inference_pb2 as inference_dot_v1_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference/v1/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/inference.v1.InferenceService/Predict',
                request_serializer=inference_dot_v1_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference_dot_v1_dot_inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.StreamPredict = channel.stream_stream(
                '/inference.v1.InferenceService/StreamPredict',
                request_serializer=inference_dot_v1_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference_dot_v1_dot_inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/inference.v1.InferenceService/Health',
                request_serializer=inference_dot_v1_dot_inference__pb2.HealthRequest.SerializeToString,
                response_deserializer=inference_dot_v1_dot_inference__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/inference.v1.InferenceService/RegisterWorker',
                request_serializer=inference_dot_v1_dot_inference__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=inference_dot_v1_dot_inference__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Predict routes a single inference request to the best available worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredict(self, request_iterator, context):
        """StreamPredict allows a client to pipeline many requests over one connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health reports router and worker-pool status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """RegisterWorker lets an inference worker announce itself to the router.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=inference_dot_v1_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference_dot_v1_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
            'StreamPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=inference_dot_v1_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference_dot_v1_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=inference_dot_v1_dot_inference__pb2.HealthRequest.FromString,
                    response_serializer=inference_dot_v1_dot_inference__pb2.HealthResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=inference_dot_v1_dot_inference__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=inference_dot_v1_dot_inference__pb2.RegisterWorkerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.v1.InferenceService/Predict',
            inference_dot_v1_dot_inference__pb2.InferenceRequest.SerializeToString,
            inference_dot_v1_dot_inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.v1.InferenceService/StreamPredict',
            inference_dot_v1_dot_inference__pb2.InferenceRequest.SerializeToString,
            inference_dot_v1_dot_inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.v1.InferenceService/Health',
            inference_dot_v1_dot_inference__pb2.HealthRequest.SerializeToString,
            inference_dot_v1_dot_inference__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.v1.InferenceService/RegisterWorker',
            inference_dot_v1_dot_inference__pb2.RegisterWorkerRequest.SerializeToString,
            inference_dot_v1_dot_inference__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
